### ISSUE TITLE
Tag for go 1.21

### ISSUE THREAD

**Issue by Hellseher** [ipfs/go-ipfs-blocksutil#25]
Hello,

During update of IPFS/Kubo in Guix we had to package `go-ipfs-blocksutil` but
the latest available tag `0.0.1` is dated to 2019. Is it possible to place a new
version tag or publish a fresh release, it would ease maintenance and packaging
in other downstram distributions, not just in Guix.

As side note, is it possible to place more details in README describing the
project please?

Thanks,
Oleg

**Comment by gammazero** [comment]
Since dependencies have been updated, I will create a new tag and release. However, you may want to consider using the [`ipfs/go-test/random`](https://pkg.go.dev/github.com/ipfs/go-test/random) package for block generation, as most test code is using that instead of this repo. See the [`BlocksOfSize`](https://pkg.go.dev/github.com/ipfs/go-test/random#BlocksOfSize) function.
